num_events: 5
num_bins: 56
terminal_events: [4]
discrete: False
event_ranks: {0: [4], 1: [4], 2: [4], 3: [4], 4: []}
event_groups: {0: [0, 1, 2, 3, 4],
              1: [0, 1, 2, 3, 4],
              2: [0, 1, 2, 3, 4],
              3: [0, 1, 2, 3, 4],
              4: [4]}
min_time: 1
max_time: 56
min_epoch: 1
max_epoch: 100