num_events: 6
num_bins: 56
terminal_events: [5]
discrete: False
event_ranks: {0: [5], 1: [5], 2: [5], 3: [5], 4: [5], 5: []}
event_groups: {0: [0, 1, 2, 3, 4, 5],
              1: [0, 1, 2, 3, 4, 5],
              2: [0, 1, 2, 3, 4, 5],
              3: [0, 1, 2, 3, 4, 5],
              4: [0, 1, 2, 3, 4, 5],
              5: [5]}
min_time: 1
max_time: 56
min_epoch: 1
max_epoch: 100