layers: [32]
lr: 0.001
n_epochs: 1000
n_dists: 3
batch_size: 32
mu_scale: Null
rho_scale: -5.0
sigma1: 1
sigma2: 0.002
pi: 1.0
n_samples_train: 10
n_samples_test: 100
verbose: True
early_stop: True
patience: 10